from django.conf.urls import url

from .views import (
        accueilDialogue,
        DialogueList,
        ElementDialogueCreate,
        elementDialogueDetail,
        ElementDialogueUpdate,
        ElementDialogueDelete,
        purgeElements,
        exporteElements,
        importeElements,
        urlMiminePost,
        formulaireAvecPost,
        viewSinodoju,
)

urlpatterns = [
    url(r'^dialogue/$',
            accueilDialogue,
                name='dialogue_accueil'),
    url(r'^dialogue/liste/$',
            DialogueList.as_view(),
                name='dialogue_liste'),
    url(r'^dialogue/element/create/$',
            ElementDialogueCreate.as_view(),
                name='dialogue_element_create'),
    url(r'^dialogue/element/(?P<nomUrl>[\w\-]+)/$',
            elementDialogueDetail,
                name='dialogue_detail'),
    url(r'^dialogue/element-update/(?P<nomUrl>[\w\-]+)/$',
            ElementDialogueUpdate.as_view(),
                name='dialogue_update'),
    url(r'^dialogue/element/(?P<nomUrl>[\w\-]+)/delete/$',
            ElementDialogueDelete.as_view(),
                name='dialogue_delete'),
    url(r'^dialogue/purge-elements/$',
            purgeElements,
                name='purge_elements'),
    url(r'^dialogue/importe-elements/$',
            importeElements,
                name='importe_elements'),
    url(r'^dialogue/exporte-elements/$',
            exporteElements,
                name='exporte_elements'),
    url(r'^dialogue/url-mimine-post$',
            urlMiminePost,
                name='url_mimine_post'),
    url(r'^dialogue/formulaire-avec-post/$',
            formulaireAvecPost,
                name='formulaire_avec_post'),
    url(r'^dialogue/url-sinodoju/$',
            viewSinodoju,
                name='nom_sinodoju'),
]
